name: Update matter_sdk Submodule

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '*/5 * * * *' # Daily at midnight
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to update'
        required: false
        default: 'main'

jobs:
  update-matter_sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target_branch: >-
          ${{
            github.event_name == 'schedule'
              && fromJson('["main","release_2.8-1.5"]')
              || fromJson(format('["{0}"]', inputs.target_branch))
          }}
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.target_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update matter_sdk submodule
        uses: SiliconLabsSoftware/matter_update_submodules@testing/no-app-auth
        with:
          target_branch: ${{ matrix.target_branch }}